# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CHOICE.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 80, 54, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 80, 161, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 170, 141, 51))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.enter)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择实验："))
        self.comboBox.setItemText(0, _translate("MainWindow", "顺序高斯消去法"))
        self.comboBox.setItemText(1, _translate("MainWindow", "选列主元高斯消去法"))
        self.comboBox.setItemText(2, _translate("MainWindow", "LU分解"))
        self.comboBox.setItemText(3, _translate("MainWindow", "紧凑格式的LU分解"))
        self.comboBox.setItemText(4, _translate("MainWindow", "二分法"))
        self.comboBox.setItemText(5, _translate("MainWindow", "牛顿迭代法"))
        self.comboBox.setItemText(6, _translate("MainWindow", "高斯赛德尔迭代"))
        self.comboBox.setItemText(7, _translate("MainWindow", "拉格朗日插值"))
        self.comboBox.setItemText(8, _translate("MainWindow", "三次样条插值"))
        self.comboBox.setItemText(9, _translate("MainWindow", "欧拉法解常微分方程"))
        self.comboBox.setItemText(10, _translate("MainWindow", "改进欧拉法解常微分方程"))
        self.comboBox.setItemText(11, _translate("MainWindow", "其他"))
        self.pushButton.setText(_translate("MainWindow", "进入实验"))
